apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: bbbipul/auth_t
    context: auth
  - image: bbbipul/client_t
    context: client
  - image: bbbipul/tickets
    context: tickets
deploy:
  kubectl:
    manifests:
    - infra/k8s/*
