apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: bbbipul/auth_t
    context: auth
  - image: bbbipul/client_t
    context: client
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/ingress-srv.yaml
